/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;
import utils.Slide;

/**
 *
 * @author HP EliteBook 8470p
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    Slide slide;
    private String msj = "Registrado!";
    
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        slide = new Slide();
    }
    
    public void moverIzquierdaInfo()
    {
        slide.jPanelXIzquierda(0, -520, 10, 5, jpInfoRegistro);
    }
    
    public void moverDerechaInfo()
    {
        slide.jPanelXDerecha(-520, 0, 10, 5, jpInfoRegistro);
    }
    
    public void moverDerchaRegistro()
    {
        slide.jPanelYAbajo(-600, 0, 10, 5, jpRegistro);
    }
    
    public void moverArribaRegistro()
    {
        slide.jPanelYArriba(0, -600, 10, 5, jpRegistro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInfoRegistro = new javax.swing.JPanel();
        jlblMsj = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnRegistro = new javax.swing.JButton();
        jpLogin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_usuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txt_pass = new javax.swing.JPasswordField();
        btn_ingreso = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpRegistro = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jbtnRegistrarDatos = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setOpacity(0.0F);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpInfoRegistro.setBackground(new java.awt.Color(98, 140, 188));
        jpInfoRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblMsj.setBackground(new java.awt.Color(255, 255, 255));
        jlblMsj.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jlblMsj.setForeground(new java.awt.Color(255, 255, 255));
        jpInfoRegistro.add(jlblMsj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 160, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imgboard.png"))); // NOI18N
        jpInfoRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 460, 320));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Clinica especializada en tratamientos odontologicos ");
        jpInfoRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 420, 50));

        jbtnRegistro.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jbtnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_RegistrarseAquiOff.png"))); // NOI18N
        jbtnRegistro.setBorder(null);
        jbtnRegistro.setBorderPainted(false);
        jbtnRegistro.setContentAreaFilled(false);
        jbtnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegistro.setFocusable(false);
        jbtnRegistro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_RegistrarseAquiOn.png"))); // NOI18N
        jbtnRegistro.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_RegistrarseAquiOn.png"))); // NOI18N
        jbtnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnRegistroMouseClicked(evt);
            }
        });
        jbtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistroActionPerformed(evt);
            }
        });
        jpInfoRegistro.add(jbtnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 260, 40));

        getContentPane().add(jpInfoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 600));

        jpLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(98, 140, 188));
        jLabel7.setFont(new java.awt.Font("Decker", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(98, 140, 188));
        jLabel7.setText("Contraseña:");
        jpLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 130, -1));

        jLabel8.setBackground(new java.awt.Color(98, 140, 188));
        jLabel8.setFont(new java.awt.Font("Decker", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(98, 140, 188));
        jLabel8.setText("Usuario:");
        jpLogin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 90, -1));

        jSeparator1.setBackground(new java.awt.Color(98, 140, 188));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jpLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 300, 10));

        txt_usuario.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(51, 51, 51));
        txt_usuario.setBorder(null);
        jpLogin.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 300, 40));

        jSeparator2.setBackground(new java.awt.Color(98, 140, 188));
        jSeparator2.setForeground(new java.awt.Color(98, 140, 188));
        jpLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 300, 10));

        txt_pass.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(51, 51, 51));
        txt_pass.setBorder(null);
        jpLogin.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 300, 40));

        btn_ingreso.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        btn_ingreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_IniciarSesionOff.png"))); // NOI18N
        btn_ingreso.setBorder(null);
        btn_ingreso.setBorderPainted(false);
        btn_ingreso.setContentAreaFilled(false);
        btn_ingreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingreso.setFocusable(false);
        btn_ingreso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_IniciarSesionOn.png"))); // NOI18N
        btn_ingreso.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_IniciarSesionOn.png"))); // NOI18N
        btn_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresoActionPerformed(evt);
            }
        });
        jpLogin.add(btn_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 260, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Compress_22px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jpLogin.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 5, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Delete_22px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jpLogin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 5, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img_contraseña.png"))); // NOI18N
        jpLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 30, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Img_Usuario.png"))); // NOI18N
        jpLogin.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 30, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Decker", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(98, 140, 188));
        jLabel5.setText("Bienvenido");
        jpLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Img_Diente.jpg"))); // NOI18N
        jpLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 260, 230));

        getContentPane().add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 480, 600));

        jpRegistro.setBackground(new java.awt.Color(255, 102, 102));
        jpRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("apellidos");
        jpRegistro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 90, 30));

        jTextField2.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jpRegistro.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, 40));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jpRegistro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 230, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jpRegistro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 230, 10));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Nombre(s)");
        jpRegistro.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 90, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Male_User_80px_1.png"))); // NOI18N
        jpRegistro.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 90, 90));

        jPasswordField3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField3.setBorder(null);
        jPasswordField3.setOpaque(false);
        jpRegistro.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 230, 40));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jpRegistro.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 230, 10));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("contraseña");
        jpRegistro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 90, 30));

        jTextField3.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jpRegistro.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 230, 40));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("edad");
        jpRegistro.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 90, 30));

        jTextField4.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(null);
        jTextField4.setOpaque(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jpRegistro.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 230, 40));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jpRegistro.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 230, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jpRegistro.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 230, 10));

        jTextField5.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);
        jTextField5.setOpaque(false);
        jpRegistro.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 230, 40));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("carrera");
        jpRegistro.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 90, 30));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jpRegistro.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 230, 10));

        jTextField6.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(null);
        jTextField6.setOpaque(false);
        jpRegistro.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 230, 40));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("correo");
        jpRegistro.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 90, 30));

        jbtnRegistrarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_listoOff.png"))); // NOI18N
        jbtnRegistrarDatos.setBorder(null);
        jbtnRegistrarDatos.setBorderPainted(false);
        jbtnRegistrarDatos.setContentAreaFilled(false);
        jbtnRegistrarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegistrarDatos.setFocusPainted(false);
        jbtnRegistrarDatos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_ListoOn.png"))); // NOI18N
        jbtnRegistrarDatos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_ListoOn.png"))); // NOI18N
        jbtnRegistrarDatos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn_ListoOn.png"))); // NOI18N
        jbtnRegistrarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnRegistrarDatosMouseClicked(evt);
            }
        });
        jbtnRegistrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarDatosActionPerformed(evt);
            }
        });
        jpRegistro.add(jbtnRegistrarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 260, 40));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/square_minimalism_colorful-170999.png"))); // NOI18N
        wallpaper.setText("jLabel13");
        jpRegistro.add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-560, 0, 1080, 600));

        getContentPane().add(jpRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -600, 520, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        try {
            int dialogButon = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "¿Desea salir del sistema?", "EXIT", dialogButon);
            if (result == 0) {
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jbtnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistroMouseClicked
        moverIzquierdaInfo();
        moverDerchaRegistro();
    }//GEN-LAST:event_jbtnRegistroMouseClicked

    private void jbtnRegistrarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistrarDatosMouseClicked
        moverArribaRegistro();
        moverDerechaInfo();
        this.jlblMsj.setText(msj + " " + jTextField3.getText());
        this.txt_usuario.setText("");
        this.jTextField2.setText("");
        this.jTextField3.setText("");
        this.jTextField4.setText("");
        this.jTextField5.setText("");
        this.jTextField6.setText("");
        this.jPasswordField3.setText("");
        
    }//GEN-LAST:event_jbtnRegistrarDatosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) 
        {//50% de transparencia
            String val = i + "F";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(100);
            } catch (Exception e) 
            {
                
            }
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void jbtnRegistrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRegistrarDatosActionPerformed

    private void jbtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRegistroActionPerformed

    private void btn_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresoActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_ingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton jbtnRegistrarDatos;
    private javax.swing.JButton jbtnRegistro;
    private javax.swing.JLabel jlblMsj;
    private javax.swing.JPanel jpInfoRegistro;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JPanel jpRegistro;
    public javax.swing.JPasswordField txt_pass;
    public javax.swing.JTextField txt_usuario;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
