/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author HP EliteBook 8470p
 */
public class ReservarCitas extends javax.swing.JFrame {

    /**
     * Creates new form Citas
     */
    public ReservarCitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        btn_AgregarCita = new javax.swing.JButton();
        btn_GuardarCita = new javax.swing.JButton();
        btn_CancelarCita = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_IdPcntCita = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_NombrePcnt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Edad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_celular = new javax.swing.JTextField();
        btnBuscarP_Agenda = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_Cita = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        radio_8_Mat = new javax.swing.JRadioButton();
        radio_830_Mat = new javax.swing.JRadioButton();
        radio_9_Mat = new javax.swing.JRadioButton();
        radio_930_Mat = new javax.swing.JRadioButton();
        radio_10_Mat = new javax.swing.JRadioButton();
        radio_1030_Mat = new javax.swing.JRadioButton();
        radio_11_Mat = new javax.swing.JRadioButton();
        radio_1130_Mat = new javax.swing.JRadioButton();
        radio_12_Ves = new javax.swing.JRadioButton();
        radio_1230_Ves = new javax.swing.JRadioButton();
        radio_13_Ves = new javax.swing.JRadioButton();
        radio_1330_Ves = new javax.swing.JRadioButton();
        radio_14_Ves = new javax.swing.JRadioButton();
        radio_1430_Ves = new javax.swing.JRadioButton();
        radio_15_Ves = new javax.swing.JRadioButton();
        radio_1530_Ves = new javax.swing.JRadioButton();
        radio_16_Ves = new javax.swing.JRadioButton();
        radio_1630_Ves = new javax.swing.JRadioButton();
        radio_17_Ves = new javax.swing.JRadioButton();
        radio_1730_Ves = new javax.swing.JRadioButton();
        radio_18_Ves = new javax.swing.JRadioButton();
        radio_1830_Ves = new javax.swing.JRadioButton();
        radio_19_Ves = new javax.swing.JRadioButton();
        radio_1930_Ves = new javax.swing.JRadioButton();
        fecha_Elegida = new com.toedter.calendar.JDateChooser();
        btnVerDisponible = new javax.swing.JButton();
        radio_20_Ves = new javax.swing.JRadioButton();
        radio_2030_Ves = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(98, 140, 188));

        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(26, 54, 168));
        jCheckBox1.setText("Reservar Citas");
        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checkdrop.png"))); // NOI18N
        jCheckBox1.setPreferredSize(new java.awt.Dimension(113, 33));

        btn_AgregarCita.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_AgregarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btn_ReproCita.png"))); // NOI18N
        btn_AgregarCita.setText("Agregar Cita");
        btn_AgregarCita.setPreferredSize(new java.awt.Dimension(73, 41));

        btn_GuardarCita.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_GuardarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btn_GuardarCita.png"))); // NOI18N
        btn_GuardarCita.setText("Guardar Cita");
        btn_GuardarCita.setPreferredSize(new java.awt.Dimension(73, 41));

        btn_CancelarCita.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_CancelarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btn_AnularCita.png"))); // NOI18N
        btn_CancelarCita.setText("Cancelar Cita");
        btn_CancelarCita.setPreferredSize(new java.awt.Dimension(73, 41));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_AgregarCita, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(btn_GuardarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CancelarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_AgregarCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_GuardarCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_CancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(552, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel1.setText("Id Paciente:");

        txt_IdPcntCita.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel4.setText("Edad:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel9.setText("Celular:");

        txt_celular.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        btnBuscarP_Agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btn_Buscar.png"))); // NOI18N
        btnBuscarP_Agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarP_AgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_NombrePcnt, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 431, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_IdPcntCita, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarP_Agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(608, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_IdPcntCita, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarP_Agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(txt_NombrePcnt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_Edad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos cita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Cita N°:");

        txt_Cita.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Cita.setForeground(new java.awt.Color(98, 140, 188));
        txt_Cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CitaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel6.setText("Fecha de la cita:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel7.setText("Horarios disponibles ");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel8.setText("Matutino ");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel10.setText("Vespertino");

        radio_8_Mat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_8_Mat.setText("8:00 - 8:30");
        radio_8_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_8_MatActionPerformed(evt);
            }
        });

        radio_830_Mat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_830_Mat.setText("8:30 - 9:00");
        radio_830_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_830_MatActionPerformed(evt);
            }
        });

        radio_9_Mat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_9_Mat.setText("9:00 - 9:30");
        radio_9_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_9_MatActionPerformed(evt);
            }
        });

        radio_930_Mat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_930_Mat.setText("9:30 - 10:00");
        radio_930_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_930_MatActionPerformed(evt);
            }
        });

        radio_10_Mat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_10_Mat.setText("10:00 - 10:30");
        radio_10_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_10_MatActionPerformed(evt);
            }
        });

        radio_1030_Mat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1030_Mat.setText("10:30 - 11:00");
        radio_1030_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1030_MatActionPerformed(evt);
            }
        });

        radio_11_Mat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_11_Mat.setText("11:00 - 11:30");
        radio_11_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_11_MatActionPerformed(evt);
            }
        });

        radio_1130_Mat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1130_Mat.setText("11:30 - 12:00");
        radio_1130_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1130_MatActionPerformed(evt);
            }
        });

        radio_12_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_12_Ves.setText("12:00 - 12:30");
        radio_12_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_12_VesActionPerformed(evt);
            }
        });

        radio_1230_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1230_Ves.setText("12:30 - 1:00");
        radio_1230_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1230_VesActionPerformed(evt);
            }
        });

        radio_13_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_13_Ves.setText("1:00 - 1:30");
        radio_13_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_13_VesActionPerformed(evt);
            }
        });

        radio_1330_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1330_Ves.setText("1:30 - 2:00");
        radio_1330_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1330_VesActionPerformed(evt);
            }
        });

        radio_14_Ves.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio_14_Ves.setText("2:00 - 2:30");
        radio_14_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_14_VesActionPerformed(evt);
            }
        });

        radio_1430_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1430_Ves.setText("2:30 - 3:00");
        radio_1430_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1430_VesActionPerformed(evt);
            }
        });

        radio_15_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_15_Ves.setText("3:00 - 3:30");
        radio_15_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_15_VesActionPerformed(evt);
            }
        });

        radio_1530_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1530_Ves.setText("3:30 - 4:00");
        radio_1530_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1530_VesActionPerformed(evt);
            }
        });

        radio_16_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_16_Ves.setText("4:00 - 4:30");
        radio_16_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_16_VesActionPerformed(evt);
            }
        });

        radio_1630_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1630_Ves.setText("4:30 - 5:00");
        radio_1630_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1630_VesActionPerformed(evt);
            }
        });

        radio_17_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_17_Ves.setText("5:00 - 5:30");
        radio_17_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_17_VesActionPerformed(evt);
            }
        });

        radio_1730_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1730_Ves.setText("5:30 - 6:00");
        radio_1730_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1730_VesActionPerformed(evt);
            }
        });

        radio_18_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_18_Ves.setText("6:00 - 6:30");
        radio_18_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_18_VesActionPerformed(evt);
            }
        });

        radio_1830_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1830_Ves.setText("6:30 - 7:00");
        radio_1830_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1830_VesActionPerformed(evt);
            }
        });

        radio_19_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_19_Ves.setText("7:00 - 7:30");
        radio_19_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_19_VesActionPerformed(evt);
            }
        });

        radio_1930_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_1930_Ves.setText("7:30 - 8:00");
        radio_1930_Ves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1930_VesActionPerformed(evt);
            }
        });

        btnVerDisponible.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnVerDisponible.setText("Ver horario disponible");

        radio_20_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_20_Ves.setText("8:00 - 8:30");

        radio_2030_Ves.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radio_2030_Ves.setText("8:30 - 9:00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha_Elegida, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Cita, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(radio_11_Mat)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio_1130_Mat))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(radio_8_Mat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_9_Mat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_10_Mat, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(radio_1030_Mat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_930_Mat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_830_Mat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(68, 68, 68)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(radio_12_Ves)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio_1230_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(radio_20_Ves, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio_2030_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(radio_19_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_13_Ves, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_14_Ves, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                            .addComponent(radio_15_Ves, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_16_Ves, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_17_Ves, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_18_Ves, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radio_1330_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_1430_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_1530_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_1630_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_1730_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_1830_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radio_1930_Ves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 67, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(129, 129, 129))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(230, 230, 230))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Cita, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(fecha_Elegida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(586, 586, 586))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_8_Mat)
                            .addComponent(radio_830_Mat))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_9_Mat)
                            .addComponent(radio_930_Mat)
                            .addComponent(radio_13_Ves)
                            .addComponent(radio_1330_Ves))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_10_Mat)
                            .addComponent(radio_1030_Mat)
                            .addComponent(radio_14_Ves)
                            .addComponent(radio_1430_Ves)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio_12_Ves)
                        .addComponent(radio_1230_Ves)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio_11_Mat)
                        .addComponent(radio_1130_Mat))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_15_Ves)
                            .addComponent(radio_1530_Ves))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_16_Ves)
                            .addComponent(radio_1630_Ves))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_17_Ves)
                            .addComponent(radio_1730_Ves))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_18_Ves)
                            .addComponent(radio_1830_Ves))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_19_Ves)
                            .addComponent(radio_1930_Ves))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_20_Ves)
                    .addComponent(radio_2030_Ves))
                .addGap(18, 18, 18)
                .addComponent(btnVerDisponible)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 547, Short.MAX_VALUE)
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CitaActionPerformed

    private void radio_8_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_8_MatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_8_MatActionPerformed

    private void radio_830_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_830_MatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_830_MatActionPerformed

    private void radio_9_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_9_MatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_9_MatActionPerformed

    private void radio_10_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_10_MatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_10_MatActionPerformed

    private void radio_1030_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1030_MatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1030_MatActionPerformed

    private void radio_11_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_11_MatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_11_MatActionPerformed

    private void radio_1130_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1130_MatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1130_MatActionPerformed

    private void radio_12_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_12_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_12_VesActionPerformed

    private void radio_1230_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1230_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1230_VesActionPerformed

    private void radio_13_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_13_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_13_VesActionPerformed

    private void radio_1330_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1330_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1330_VesActionPerformed

    private void radio_14_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_14_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_14_VesActionPerformed

    private void radio_1430_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1430_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1430_VesActionPerformed

    private void radio_15_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_15_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_15_VesActionPerformed

    private void radio_1530_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1530_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1530_VesActionPerformed

    private void radio_16_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_16_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_16_VesActionPerformed

    private void radio_1630_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1630_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1630_VesActionPerformed

    private void radio_17_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_17_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_17_VesActionPerformed

    private void radio_1730_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1730_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1730_VesActionPerformed

    private void radio_18_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_18_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_18_VesActionPerformed

    private void radio_1830_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1830_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1830_VesActionPerformed

    private void radio_19_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_19_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_19_VesActionPerformed

    private void radio_1930_VesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1930_VesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1930_VesActionPerformed

    private void radio_930_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_930_MatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_930_MatActionPerformed

    private void btnBuscarP_AgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarP_AgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarP_AgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservarCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarP_Agenda;
    public javax.swing.JButton btnVerDisponible;
    public javax.swing.JButton btn_AgregarCita;
    public javax.swing.JButton btn_CancelarCita;
    public javax.swing.JButton btn_GuardarCita;
    public com.toedter.calendar.JDateChooser fecha_Elegida;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JRadioButton radio_1030_Mat;
    public javax.swing.JRadioButton radio_10_Mat;
    public javax.swing.JRadioButton radio_1130_Mat;
    public javax.swing.JRadioButton radio_11_Mat;
    public javax.swing.JRadioButton radio_1230_Ves;
    public javax.swing.JRadioButton radio_12_Ves;
    public javax.swing.JRadioButton radio_1330_Ves;
    public javax.swing.JRadioButton radio_13_Ves;
    public javax.swing.JRadioButton radio_1430_Ves;
    public javax.swing.JRadioButton radio_14_Ves;
    public javax.swing.JRadioButton radio_1530_Ves;
    public javax.swing.JRadioButton radio_15_Ves;
    public javax.swing.JRadioButton radio_1630_Ves;
    public javax.swing.JRadioButton radio_16_Ves;
    public javax.swing.JRadioButton radio_1730_Ves;
    public javax.swing.JRadioButton radio_17_Ves;
    public javax.swing.JRadioButton radio_1830_Ves;
    public javax.swing.JRadioButton radio_18_Ves;
    public javax.swing.JRadioButton radio_1930_Ves;
    public javax.swing.JRadioButton radio_19_Ves;
    public javax.swing.JRadioButton radio_2030_Ves;
    public javax.swing.JRadioButton radio_20_Ves;
    public javax.swing.JRadioButton radio_830_Mat;
    public javax.swing.JRadioButton radio_8_Mat;
    public javax.swing.JRadioButton radio_930_Mat;
    public javax.swing.JRadioButton radio_9_Mat;
    public javax.swing.JTextField txt_Cita;
    public javax.swing.JTextField txt_Edad;
    public javax.swing.JTextField txt_IdPcntCita;
    public javax.swing.JTextField txt_NombrePcnt;
    public javax.swing.JTextField txt_celular;
    // End of variables declaration//GEN-END:variables
}
